INSERT INTO enriched_data (
    order_id,
    market_timestamp,
    symbol,
    market,
    volume,
    open_price,
    high_price,
    low_price,
    close_price,
    num_trades,
    volume_weighted_price,
    pct_return,
    log_return,
    sma_10,
    sma_20,
    sma_50,
    sma_100,
    sma_150,
    sma_200,
    macd,
    macd_signal,
    rsi,
    ema_9,
    ema_10,
    ema_12,
    ema_20,
    ema_26,
    ema_50,
    ema_100,
    ema_150,
    ema_200,
    volatility_10,
    volatility_20,
    volatility_50,
    atr_14,
    hist_volatility_20,
    range,
    body,
    upper_wick,
    lower_wick,
    vol_ma_10,
    vol_ma_20,
    vol_ma_50,
    vol_ma_100,
    vol_ma_200,
    vol_change,
    vwap_10,
    vwap_20,
    vwap_50,
    vwap_100,
    vwap_150,
    vwap_200,
    hour,
    day_of_week,
    adx,
    momentum_10,
    roc_10,
    stochastic_k,
    stochastic_d,
    bollinger_upper,
    bollinger_lower,
    bollinger_width,
    gap,
    high_low_ratio,
    obv,
    adl
) VALUES (
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
) RETURNING id;