import logging
from enum import Enum


class EnvLoggerTypeDevIntegration(Enum):
    ## DATABASE
    DATABASE = ("DEV_INTEGRATION_DATABASE", logging.ERROR)

    ## DAOS
    DATA_STREAM_SESSION_DAO = ("DEV_INTEGRATION_DATA_STREAM_SESSION_DAO", logging.ERROR)
    ENRICHED_DATA_DAO = ("DEV_INTEGRATION_ENRICHED_DATA_DAO", logging.ERROR)
    TRADE_DAO = ("DEV_INTEGRATION_TRADE_DAO", logging.ERROR)
    ORDER_DAO = ("DEV_INTEGRATION_ORDER_DAO", logging.ERROR)

    ## REPOSITORIES
    DATA_STREAM_SESSION_REPO = (
        "DEV_INTEGRATION_DATA_STREAM_SESSION_REPO",
        logging.ERROR,
    )
    ENRICHED_DATA_REPO = ("DEV_INTEGRATION_ENRICHED_DATA_REPO", logging.ERROR)
    TRADE_REPO = ("DEV_INTEGRATION_TRADE_REPO", logging.ERROR)
    ORDER_REPO = ("DEV_INTEGRATION_ORDER_REPO", logging.ERROR)
    WATCHLIST_REPO = ("DEV_INTEGRATION_WATCHLIST_REPO", logging.ERROR)

    ## ALPACA CLIENTS
    CLIENT_CONTAINER = ("DEV_INTEGRATION_CLIENT_CONTAINER", logging.ERROR)
    ALPACA_CORPORATE_ACTION_CLIENT = (
        "DEV_INTEGRATION_ALPACA_CORPORATE_ACTION_CLIENT",
        logging.ERROR,
    )
    ALPACA_NEWS_CLIENT = ("DEV_INTEGRATION_ALPACA_NEWS_CLIENT", logging.ERROR)
    ALPACA_SCREENER_CLIENT = ("DEV_INTEGRATION_ALPACA_SCREENER_CLIENT", logging.ERROR)
    ALPACA_STOCK_CLIENT = ("DEV_INTEGRATION_ALPACA_STOCK_CLIENT", logging.ERROR)
    ALPACA_STREAM_CLIENT = ("DEV_INTEGRATION_ALPACA_STREAM_CLIENT", logging.ERROR)
    ALPACA_ORDER_STREAM_CLIENT = (
        "DEV_INTEGRATION_ALPACA_ORDER_STREAM_CLIENT",
        logging.ERROR,
    )
    ALPACA_ACCOUNT_CLIENT = ("DEV_INTEGRATION_ALPACA_ACCOUNT_CLIENT", logging.ERROR)
    ALPACA_ASSETS_CLIENT = ("DEV_INTEGRATION_ALPACA_ASSETS_CLIENT", logging.ERROR)
    ALPACA_CALENDAR_CLIENT = ("DEV_INTEGRATION_ALPACA_CALENDAR_CLIENT", logging.ERROR)
    ALPACA_CLOCK_CLIENT = ("DEV_INTEGRATION_ALPACA_CLOCK_CLIENT", logging.ERROR)
    ALPACA_ORDERS_CLIENT = ("DEV_INTEGRATION_ALPACA_ORDERS_CLIENT", logging.ERROR)
    ALPACA_PORTFOLIO_CLIENT = ("DEV_INTEGRATION_ALPACA_PORTFOLIO_CLIENT", logging.ERROR)
    ALPACA_POSITIONS_CLIENT = ("DEV_INTEGRATION_ALPACA_POSITIONS_CLIENT", logging.ERROR)
    ALPACA_WATCHLIST_CLIENT = ("DEV_INTEGRATION_ALPACA_WATCHLIST_CLIENT", logging.ERROR)

    ## ADAPTERS
    CORPORATE_ACTION_ADAPTER = (
        "DEV_INTEGRATION_CORPORATE_ACTION_ADAPTER",
        logging.ERROR,
    )
    NEWS_ADAPTER = ("DEV_INTEGRATION_NEWS_ADAPTER", logging.ERROR)
    SCREENER_ADAPTER = ("DEV_INTEGRATION_SCREENER_ADAPTER", logging.ERROR)
    QUOTE_ADAPTER = ("DEV_INTEGRATION_QUOTE_ADAPTER", logging.ERROR)
    STREAM_ADAPTER = ("DEV_INTEGRATION_STREAM_ADAPTER", logging.ERROR)
    ACCOUNT_ADAPTER = ("DEV_INTEGRATION_ACCOUNT_ADAPTER", logging.ERROR)
    ASSETS_ADAPTER = ("DEV_INTEGRATION_ASSETS_ADAPTER", logging.ERROR)
    CALENDAR_ADAPTER = ("DEV_INTEGRATION_CALENDAR_ADAPTER", logging.ERROR)
    CLOCK_ADAPTER = ("DEV_INTEGRATION_CLOCK_ADAPTER", logging.ERROR)
    ORDER_STREAM_ADAPTER = ("DEV_INTEGRATION_ORDER_STREAM_ADAPTER", logging.ERROR)
    ORDERS_ADAPTER = ("DEV_INTEGRATION_ORDERS_ADAPTER", logging.ERROR)
    PORTFOLIO_ADAPTER = ("DEV_INTEGRATION_PORTFOLIO_ADAPTER", logging.ERROR)
    POSITIONS_ADAPTER = ("DEV_INTEGRATION_POSITIONS_ADAPTER", logging.ERROR)
    WATCHLIST_ADAPTER = ("DEV_INTEGRATION_WATCHLIST_ADAPTER", logging.ERROR)

    ## STAGE DATA
    STAGE_DATA_MANAGER = ("DEV_INTEGRATION_STAGE_DATA_MANAGER", logging.ERROR)
    STAGE_DATA_PREPARER = ("DEV_INTEGRATION_STAGE_DATA_PREPARER", logging.ERROR)
    STAGE_DATA_WRITER = ("DEV_INTEGRATION_STAGE_DATA_WRITER", logging.ERROR)
    STAGE_DATA_LOADER = ("DEV_INTEGRATION_STAGE_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_MANAGER = (
        "DEV_INTEGRATION_SYMBOL_STRATEGY_DATA_MANAGER",
        logging.ERROR,
    )
    SYMBOL_STRATEGY_DATA_LOADER = (
        "DEV_INTEGRATION_SYMBOL_STRATEGY_DATA_LOADER",
        logging.ERROR,
    )
    SYMBOL_STRATEGY_DATA_WRITER = (
        "DEV_INTEGRATION_SYMBOL_STRATEGY_DATA_WRITER",
        logging.ERROR,
    )

    ## FEATURE ENGINEERING
    FEATURE_ENGINEERING = ("DEV_INTEGRATION_FEATURE_ENGINEERING", logging.ERROR)
    FEATURE_ENGINEER = ("DEV_INTEGRATION_FEATURE_ENGINEER", logging.ERROR)

    ## DATA PREP
    BACKTEST_DATA_INGEST = (
        "DEV_INTEGRATION_BACKTEST_DATA_INGEST",
        logging.ERROR,
    )
    BACKTEST_FEATURE_ENGINEERING = (
        "DEV_INTEGRATION_BACKTEST_FEATURE_ENGINEERING",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY
    SIGNAL_STRATEGY = ("DEV_INTEGRATION_SIGNAL_STRATEGY", logging.ERROR)
    SIGNAL_STRATEGY_FACTORY = ("DEV_INTEGRATION_SIGNAL_STRATEGY_FACTORY", logging.ERROR)
    SIGNAL_STRATEGY_COMBINATOR_FACTORY = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_OPTIMIZER_FACTORY = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY BACKTESTING
    SIGNAL_STRATEGY_EXECUTOR = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_EXECUTOR",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_EVALUATOR = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_EVALUATOR",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_OPTIMIZATION = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_OPTIMIZATION",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_TESTING = ("DEV_INTEGRATION_SIGNAL_STRATEGY_TESTING", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATION = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_EVALUATION",
        logging.ERROR,
    )
    SYMBOL_EVALUATION = ("DEV_INTEGRATION_SYMBOL_EVALUATION", logging.ERROR)
    SIGNAL_STRATEGY_WALK_FORWARD = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_WALK_FORWARD",
        logging.ERROR,
    )

    ## PORTFOLIO STRATEGY
    PORTFOLIO_STRATEGY = ("DEV_INTEGRATION_PORTFOLIO_STRATEGY", logging.ERROR)
    PORTFOLIO_STRATEGY_COMBINATOR_FACTORY = (
        "DEV_INTEGRATION_PORTFOLIO_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY = (
        "DEV_INTEGRATION_PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## PORTFOLIO BACKTESTING
    PORTFOLIO_BACKTEST_EXECUTOR = (
        "DEV_INTEGRATION_PORTFOLIO_BACKTEST_EXECUTOR",
        logging.ERROR,
    )
    PORTFOLIO_BACKTEST_EVALUATOR = (
        "DEV_INTEGRATION_PORTFOLIO_BACKTEST_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_ASSET_MATRIX_PREPARER = (
        "DEV_INTEGRATION_PORTFOLIO_ASSET_MATRIX_PREPARER",
        logging.ERROR,
    )
    PORTFOLIO_MATRIX_LOADER = ("DEV_INTEGRATION_PORTFOLIO_MATRIX_LOADER", logging.ERROR)
    PORTFOLIO_OPTIMIZATION = ("DEV_INTEGRATION_PORTFOLIO_OPTIMIZATION", logging.ERROR)
    PORTFOLIO_TESTING = ("DEV_INTEGRATION_PORTFOLIO_TESTING", logging.ERROR)
    PORTFOLIO_WALK_FORWARD = ("DEV_INTEGRATION_PORTFOLIO_WALK_FORWARD", logging.ERROR)
    PORTFOLIO_CROSS_WINDOW_EVALUATOR = (
        "DEV_INTEGRATION_PORTFOLIO_CROSS_WINDOW_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_CROSS_STRATEGY_SUMMARY = (
        "DEV_INTEGRATION_PORTFOLIO_CROSS_STRATEGY_SUMMARY",
        logging.ERROR,
    )
    PORTFOLIO_EVALUATION = ("DEV_INTEGRATION_PORTFOLIO_EVALUATION", logging.ERROR)

    ## LEDGER SERVICES
    ACCOUNT_CASH_SERVICE = ("DEV_INTEGRATION_ACCOUNT_CASH_SERVICE", logging.ERROR)
    CLOCK_SERVICE = ("DEV_INTEGRATION_CLOCK_SERVICE", logging.ERROR)
    ENRICHED_DATA_SERVICE = ("DEV_INTEGRATION_ENRICHED_DATA_SERVICE", logging.ERROR)
    ORDER_SERVICE = ("DEV_INTEGRATION_ORDER_SERVICE", logging.ERROR)
    TRADE_SERVICE = ("DEV_INTEGRATION_TRADE_SERVICE", logging.ERROR)
    POSITION_SERVICE = ("DEV_INTEGRATION_POSITION_SERVICE", logging.ERROR)
    LEDGER_SERVICE = ("DEV_INTEGRATION_LEDGER_SERVICE", logging.ERROR)

    ## MARKET SESSION

    ORDER_EXECUTION_SERVICE = ("DEV_INTEGRATION_ORDER_EXECUTION_SERVICE", logging.ERROR)
    ORDER_MONITOR_SERVICE = ("DEV_INTEGRATION_ORDER_MONITOR_SERVICE", logging.ERROR)
    MARKET_SESSION_SERVICE = ("DEV_INTEGRATION_MARKET_SESSION_SERVICE", logging.ERROR)

    ## ORDER GENERATION
    MARKET_DATA_RAW_STREAMER = (
        "DEV_INTEGRATION_MARKET_DATA_RAW_STREAMER",
        logging.ERROR,
    )
    MARKET_DATA_ENRICHED_STREAMER = (
        "DEV_INTEGRATION_MARKET_DATA_ENRICHED_STREAMER",
        logging.ERROR,
    )
    SIGNAL_GENERATOR = ("DEV_INTEGRATION_SIGNAL_GENERATOR", logging.ERROR)
    ORDER_GENERATOR = ("DEV_INTEGRATION_ORDER_GENERATOR", logging.ERROR)
    SYMBOL_SERVICE = ("DEV_INTEGRATION_SYMBOL_SERVICE", logging.ERROR)
    ORDER_EVENT_SERVICE = ("DEV_INTEGRATION_ORDER_EVENT_SERVICE", logging.ERROR)
    SYMBOL_HOLD_TRACKER = ("DEV_INTEGRATION_SYMBOL_HOLD_TRACKER", logging.ERROR)
    SYMBOL_HOLD_SERVICE = ("DEV_INTEGRATION_SYMBOL_HOLD_SERVICE", logging.ERROR)
    ORDER_GENERATOR_SERVICE = ("DEV_INTEGRATION_ORDER_GENERATOR_SERVICE", logging.ERROR)

    # REGISTRY
    SIGNAL_STRATEGY_REGISTRY = (
        "DEV_INTEGRATION_SIGNAL_STRATEGY_REGISTRY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_REGISTRY = (
        "DEV_INTEGRATION_PORTFOLIO_STRATEGY_REGISTRY",
        logging.ERROR,
    )

    ## BACKTEST PIPELINE
    PIPELINE_COORDINATOR = ("DEV_INTEGRATION_PIPELINE_COORDINATOR", logging.ERROR)

    ## TRADE ORCHESTRATOR
    TRADE_ORCHESTRATOR = ("DEV_INTEGRATION_TRADE_ORCHESTRATOR", logging.ERROR)

    @property
    def name_str(self):
        return self.value[0]

    @property
    def log_level(self):
        return self.value[1]

    @property
    def print_logs(self):
        return self.value[2] if len(self.value) > 2 else False
