import logging
from enum import Enum


class EnvLoggerTypeProdLive(Enum):
    ## DATABASE
    DATABASE = ("PROD_LIVE_DATABASE", logging.ERROR)

    ## DAOS
    DATA_STREAM_SESSION_DAO = ("PROD_LIVE_DATA_STREAM_SESSION_DAO", logging.ERROR)
    ENRICHED_DATA_DAO = ("PROD_LIVE_ENRICHED_DATA_DAO", logging.ERROR)
    TRADE_DAO = ("PROD_LIVE_TRADE_DAO", logging.ERROR)
    ORDER_DAO = ("PROD_LIVE_ORDER_DAO", logging.ERROR)

    ## REPOSITORIES
    DATA_STREAM_SESSION_REPO = ("PROD_LIVE_DATA_STREAM_SESSION_REPO", logging.ERROR)
    ENRICHED_DATA_REPO = ("PROD_LIVE_ENRICHED_DATA_REPO", logging.ERROR)
    TRADE_REPO = ("PROD_LIVE_TRADE_REPO", logging.ERROR)
    ORDER_REPO = ("PROD_LIVE_ORDER_REPO", logging.ERROR)
    WATCHLIST_REPO = ("PROD_LIVE_WATCHLIST_REPO", logging.ERROR)

    ## ALPACA CLIENTS
    CLIENT_CONTAINER = ("PROD_LIVE_CLIENT_CONTAINER", logging.ERROR)
    ALPACA_CORPORATE_ACTION_CLIENT = (
        "PROD_LIVE_ALPACA_CORPORATE_ACTION_CLIENT",
        logging.ERROR,
    )
    ALPACA_NEWS_CLIENT = ("PROD_LIVE_ALPACA_NEWS_CLIENT", logging.ERROR)
    ALPACA_SCREENER_CLIENT = ("PROD_LIVE_ALPACA_SCREENER_CLIENT", logging.ERROR)
    ALPACA_STOCK_CLIENT = ("PROD_LIVE_ALPACA_STOCK_CLIENT", logging.ERROR)
    ALPACA_STREAM_CLIENT = ("PROD_LIVE_ALPACA_STREAM_CLIENT", logging.ERROR)
    ALPACA_ORDER_STREAM_CLIENT = ("PROD_LIVE_ALPACA_ORDER_STREAM_CLIENT", logging.ERROR)
    ALPACA_ACCOUNT_CLIENT = ("PROD_LIVE_ALPACA_ACCOUNT_CLIENT", logging.ERROR)
    ALPACA_ASSETS_CLIENT = ("PROD_LIVE_ALPACA_ASSETS_CLIENT", logging.ERROR)
    ALPACA_CALENDAR_CLIENT = ("PROD_LIVE_ALPACA_CALENDAR_CLIENT", logging.ERROR)
    ALPACA_CLOCK_CLIENT = ("PROD_LIVE_ALPACA_CLOCK_CLIENT", logging.ERROR)
    ALPACA_ORDERS_CLIENT = ("PROD_LIVE_ALPACA_ORDERS_CLIENT", logging.ERROR)
    ALPACA_PORTFOLIO_CLIENT = ("PROD_LIVE_ALPACA_PORTFOLIO_CLIENT", logging.ERROR)
    ALPACA_POSITIONS_CLIENT = ("PROD_LIVE_ALPACA_POSITIONS_CLIENT", logging.ERROR)
    ALPACA_WATCHLIST_CLIENT = ("PROD_LIVE_ALPACA_WATCHLIST_CLIENT", logging.ERROR)

    ## ADAPTERS
    CORPORATE_ACTION_ADAPTER = ("PROD_LIVE_CORPORATE_ACTION_ADAPTER", logging.ERROR)
    NEWS_ADAPTER = ("PROD_LIVE_NEWS_ADAPTER", logging.ERROR)
    SCREENER_ADAPTER = ("PROD_LIVE_SCREENER_ADAPTER", logging.ERROR)
    QUOTE_ADAPTER = ("PROD_LIVE_QUOTE_ADAPTER", logging.ERROR)
    STREAM_ADAPTER = ("PROD_LIVE_STREAM_ADAPTER", logging.ERROR)
    ACCOUNT_ADAPTER = ("PROD_LIVE_ACCOUNT_ADAPTER", logging.ERROR)
    ASSETS_ADAPTER = ("PROD_LIVE_ASSETS_ADAPTER", logging.ERROR)
    CALENDAR_ADAPTER = ("PROD_LIVE_CALENDAR_ADAPTER", logging.ERROR)
    CLOCK_ADAPTER = ("PROD_LIVE_CLOCK_ADAPTER", logging.ERROR)
    ORDER_STREAM_ADAPTER = ("PROD_LIVE_ORDER_STREAM_ADAPTER", logging.ERROR)
    ORDERS_ADAPTER = ("PROD_LIVE_ORDERS_ADAPTER", logging.ERROR)
    PORTFOLIO_ADAPTER = ("PROD_LIVE_PORTFOLIO_ADAPTER", logging.ERROR)
    POSITIONS_ADAPTER = ("PROD_LIVE_POSITIONS_ADAPTER", logging.ERROR)
    WATCHLIST_ADAPTER = ("PROD_LIVE_WATCHLIST_ADAPTER", logging.ERROR)

    ## STAGE DATA
    STAGE_DATA_MANAGER = ("PROD_LIVE_STAGE_DATA_MANAGER", logging.ERROR)
    STAGE_DATA_PREPARER = ("PROD_LIVE_STAGE_DATA_PREPARER", logging.ERROR)
    STAGE_DATA_WRITER = ("PROD_LIVE_STAGE_DATA_WRITER", logging.ERROR)
    STAGE_DATA_LOADER = ("PROD_LIVE_STAGE_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_MANAGER = (
        "PROD_LIVE_SYMBOL_STRATEGY_DATA_MANAGER",
        logging.ERROR,
    )
    SYMBOL_STRATEGY_DATA_LOADER = (
        "PROD_LIVE_SYMBOL_STRATEGY_DATA_LOADER",
        logging.ERROR,
    )
    SYMBOL_STRATEGY_DATA_WRITER = (
        "PROD_LIVE_SYMBOL_STRATEGY_DATA_WRITER",
        logging.ERROR,
    )

    ## FEATURE ENGINEERING
    FEATURE_ENGINEERING = ("PROD_LIVE_FEATURE_ENGINEERING", logging.ERROR)
    FEATURE_ENGINEER = ("PROD_LIVE_FEATURE_ENGINEER", logging.ERROR)

    ## DATA PREP
    BACKTEST_DATA_INGEST = ("PROD_LIVE_BACKTEST_DATA_INGEST", logging.ERROR)
    BACKTEST_FEATURE_ENGINEERING = (
        "PROD_LIVE_BACKTEST_FEATURE_ENGINEERING",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY
    SIGNAL_STRATEGY = ("PROD_LIVE_SIGNAL_STRATEGY", logging.ERROR)
    SIGNAL_STRATEGY_FACTORY = ("PROD_LIVE_SIGNAL_STRATEGY_FACTORY", logging.ERROR)
    SIGNAL_STRATEGY_COMBINATOR_FACTORY = (
        "PROD_LIVE_SIGNAL_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_OPTIMIZER_FACTORY = (
        "PROD_LIVE_SIGNAL_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY BACKTESTING
    SIGNAL_STRATEGY_EXECUTOR = ("PROD_LIVE_SIGNAL_STRATEGY_EXECUTOR", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATOR = ("PROD_LIVE_SIGNAL_STRATEGY_EVALUATOR", logging.ERROR)
    SIGNAL_STRATEGY_OPTIMIZATION = (
        "PROD_LIVE_SIGNAL_STRATEGY_OPTIMIZATION",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_TESTING = ("PROD_LIVE_SIGNAL_STRATEGY_TESTING", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATION = ("PROD_LIVE_SIGNAL_STRATEGY_EVALUATION", logging.ERROR)
    SYMBOL_EVALUATION = ("PROD_LIVE_SYMBOL_EVALUATION", logging.ERROR)
    SIGNAL_STRATEGY_WALK_FORWARD = (
        "PROD_LIVE_SIGNAL_STRATEGY_WALK_FORWARD",
        logging.ERROR,
    )

    ## PORTFOLIO STRATEGY
    ASSET_MATRIX_PREPARER = ("PROD_LIVE_ASSET_MATRIX_PREPARER", logging.ERROR)
    PORTFOLIO_STRATEGY = ("PROD_LIVE_PORTFOLIO_STRATEGY", logging.ERROR)
    PORTFOLIO_STRATEGY_COMBINATOR_FACTORY = (
        "PROD_LIVE_PORTFOLIO_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY = (
        "PROD_LIVE_PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_FACTORY = ("PROD_LIVE_PORTFOLIO_STRATEGY_FACTORY", logging.ERROR)

    ## PORTFOLIO BACKTESTING
    PORTFOLIO_BACKTEST_EXECUTOR = (
        "PROD_LIVE_PORTFOLIO_BACKTEST_EXECUTOR",
        logging.ERROR,
    )
    PORTFOLIO_BACKTEST_EVALUATOR = (
        "PROD_LIVE_PORTFOLIO_BACKTEST_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_ASSET_MATRIX_PREPARER = (
        "PROD_LIVE_PORTFOLIO_ASSET_MATRIX_PREPARER",
        logging.ERROR,
    )
    PORTFOLIO_MATRIX_LOADER = ("PROD_LIVE_PORTFOLIO_MATRIX_LOADER", logging.ERROR)
    PORTFOLIO_OPTIMIZATION = ("PROD_LIVE_PORTFOLIO_OPTIMIZATION", logging.ERROR)
    PORTFOLIO_TESTING = ("PROD_LIVE_PORTFOLIO_TESTING", logging.ERROR)
    PORTFOLIO_WALK_FORWARD = ("PROD_LIVE_PORTFOLIO_WALK_FORWARD", logging.ERROR)
    PORTFOLIO_CROSS_WINDOW_EVALUATOR = (
        "PROD_LIVE_PORTFOLIO_CROSS_WINDOW_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_CROSS_STRATEGY_SUMMARY = (
        "PROD_LIVE_PORTFOLIO_CROSS_STRATEGY_SUMMARY",
        logging.ERROR,
    )
    PORTFOLIO_EVALUATION = ("PROD_LIVE_PORTFOLIO_EVALUATION", logging.ERROR)

    ## LEDGER SERVICES
    ACCOUNT_CASH_SERVICE = ("PROD_LIVE_ACCOUNT_CASH_SERVICE", logging.ERROR)
    CLOCK_SERVICE = ("PROD_LIVE_CLOCK_SERVICE", logging.ERROR)
    ENRICHED_DATA_SERVICE = ("PROD_LIVE_ENRICHED_DATA_SERVICE", logging.ERROR)
    ORDER_SERVICE = ("PROD_LIVE_ORDER_SERVICE", logging.ERROR)
    TRADE_SERVICE = ("PROD_LIVE_TRADE_SERVICE", logging.ERROR)
    POSITION_SERVICE = ("PROD_LIVE_POSITION_SERVICE", logging.ERROR)
    LEDGER_SERVICE = ("PROD_LIVE_LEDGER_SERVICE", logging.ERROR)

    ## MARKET SESSION

    ORDER_EXECUTION_SERVICE = ("PROD_LIVE_ORDER_EXECUTION_SERVICE", logging.ERROR)
    ORDER_MONITOR_SERVICE = ("PROD_LIVE_ORDER_MONITOR_SERVICE", logging.ERROR)
    MARKET_SESSION_SERVICE = ("PROD_LIVE_MARKET_SESSION_SERVICE", logging.ERROR)

    ## ORDER GENERATION
    MARKET_DATA_RAW_STREAMER = ("PROD_LIVE_MARKET_DATA_RAW_STREAMER", logging.ERROR)
    MARKET_DATA_ENRICHED_STREAMER = (
        "PROD_LIVE_MARKET_DATA_ENRICHED_STREAMER",
        logging.ERROR,
    )
    SIGNAL_GENERATOR = ("PROD_LIVE_SIGNAL_GENERATOR", logging.ERROR)
    ORDER_GENERATOR = ("PROD_LIVE_ORDER_GENERATOR", logging.ERROR)
    SYMBOL_SERVICE = ("PROD_LIVE_SYMBOL_SERVICE", logging.ERROR)
    ORDER_EVENT_SERVICE = ("PROD_LIVE_ORDER_EVENT_SERVICE", logging.ERROR)
    SYMBOL_HOLD_TRACKER = ("PROD_LIVE_SYMBOL_HOLD_TRACKER", logging.ERROR)
    SYMBOL_HOLD_SERVICE = ("PROD_LIVE_SYMBOL_HOLD_SERVICE", logging.ERROR)
    ORDER_GENERATOR_SERVICE = ("PROD_LIVE_ORDER_GENERATOR_SERVICE", logging.ERROR)

    # REGISTRY
    SIGNAL_STRATEGY_REGISTRY = ("PROD_LIVE_SIGNAL_STRATEGY_REGISTRY", logging.ERROR)
    PORTFOLIO_STRATEGY_REGISTRY = (
        "PROD_LIVE_PORTFOLIO_STRATEGY_REGISTRY",
        logging.ERROR,
    )

    ## BACKTEST PIPELINE
    PIPELINE_COORDINATOR = ("PROD_LIVE_PIPELINE_COORDINATOR", logging.ERROR)

    ## TRADE ORCHESTRATOR
    TRADE_ORCHESTRATOR = ("PROD_LIVE_TRADE_ORCHESTRATOR", logging.ERROR)

    @property
    def name_str(self):
        return self.value[0]

    @property
    def log_level(self):
        return self.value[1]

    @property
    def print_logs(self):
        return self.value[2] if len(self.value) > 2 else False
