import logging
from enum import Enum


class EnvLoggerTypeTest(Enum):
    ## DATABASE
    DATABASE = ("TEST_DATABASE", logging.ERROR)

    ## DAOS
    DATA_STREAM_SESSION_DAO = ("TEST_DATA_STREAM_SESSION_DAO", logging.ERROR)
    ENRICHED_DATA_DAO = ("TEST_ENRICHED_DATA_DAO", logging.ERROR)
    TRADE_DAO = ("TEST_TRADE_DAO", logging.ERROR)
    ORDER_DAO = ("TEST_ORDER_DAO", logging.ERROR)

    ## REPOSITORIES
    DATA_STREAM_SESSION_REPO = ("TEST_DATA_STREAM_SESSION_REPO", logging.ERROR)
    ENRICHED_DATA_REPO = ("TEST_ENRICHED_DATA_REPO", logging.ERROR)
    TRADE_REPO = ("TEST_TRADE_REPO", logging.ERROR)
    ORDER_REPO = ("TEST_ORDER_REPO", logging.ERROR)
    WATCHLIST_REPO = ("TEST_WATCHLIST_REPO", logging.ERROR)

    ## ALPACA CLIENTS
    ALPACA_CORPORATE_ACTION_CLIENT = (
        "TEST_ALPACA_CORPORATE_ACTION_CLIENT",
        logging.ERROR,
    )
    ALPACA_NEWS_CLIENT = ("TEST_ALPACA_NEWS_CLIENT", logging.ERROR)
    ALPACA_SCREENER_CLIENT = ("TEST_ALPACA_SCREENER_CLIENT", logging.ERROR)
    ALPACA_STOCK_CLIENT = ("TEST_ALPACA_STOCK_CLIENT", logging.ERROR)
    ALPACA_STREAM_CLIENT = ("TEST_ALPACA_STREAM_CLIENT", logging.ERROR)
    ALPACA_ORDER_STREAM_CLIENT = ("TEST_ALPACA_ORDER_STREAM_CLIENT", logging.ERROR)
    ALPACA_ACCOUNT_CLIENT = ("TEST_ALPACA_ACCOUNT_CLIENT", logging.ERROR)
    ALPACA_ASSETS_CLIENT = ("TEST_ALPACA_ASSETS_CLIENT", logging.ERROR)
    ALPACA_CALENDAR_CLIENT = ("TEST_ALPACA_CALENDAR_CLIENT", logging.ERROR)
    ALPACA_CLOCK_CLIENT = ("TEST_ALPACA_CLOCK_CLIENT", logging.ERROR)
    ALPACA_ORDERS_CLIENT = ("TEST_ALPACA_ORDERS_CLIENT", logging.ERROR)
    ALPACA_PORTFOLIO_CLIENT = ("TEST_ALPACA_PORTFOLIO_CLIENT", logging.ERROR)
    ALPACA_POSITIONS_CLIENT = ("TEST_ALPACA_POSITIONS_CLIENT", logging.ERROR)
    ALPACA_WATCHLIST_CLIENT = ("TEST_ALPACA_WATCHLIST_CLIENT", logging.ERROR)

    ## ADAPTERS
    CORPORATE_ACTION_ADAPTER = ("TEST_CORPORATE_ACTION_ADAPTER", logging.ERROR)
    NEWS_ADAPTER = ("TEST_NEWS_ADAPTER", logging.ERROR)
    SCREENER_ADAPTER = ("TEST_SCREENER_ADAPTER", logging.ERROR)
    QUOTE_ADAPTER = ("TEST_QUOTE_ADAPTER", logging.ERROR)
    STREAM_ADAPTER = ("TEST_STREAM_ADAPTER", logging.ERROR)
    ACCOUNT_ADAPTER = ("TEST_ACCOUNT_ADAPTER", logging.ERROR)
    ASSETS_ADAPTER = ("TEST_ASSETS_ADAPTER", logging.ERROR)
    CALENDAR_ADAPTER = ("TEST_CALENDAR_ADAPTER", logging.ERROR)
    CLOCK_ADAPTER = ("TEST_CLOCK_ADAPTER", logging.ERROR)
    ORDER_STREAM_ADAPTER = ("TEST_ORDER_STREAM_ADAPTER", logging.ERROR)
    ORDERS_ADAPTER = ("TEST_ORDERS_ADAPTER", logging.ERROR)
    PORTFOLIO_ADAPTER = ("TEST_PORTFOLIO_ADAPTER", logging.ERROR)
    POSITIONS_ADAPTER = ("TEST_POSITIONS_ADAPTER", logging.ERROR)
    WATCHLIST_ADAPTER = ("TEST_WATCHLIST_ADAPTER", logging.ERROR)

    ## STAGE DATA
    STAGE_DATA_MANAGER = ("TEST_STAGE_DATA_MANAGER", logging.ERROR)
    STAGE_DATA_PREPARER = ("TEST_STAGE_DATA_PREPARER", logging.ERROR)
    STAGE_DATA_WRITER = ("TEST_STAGE_DATA_WRITER", logging.ERROR)
    STAGE_DATA_LOADER = ("TEST_STAGE_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_MANAGER = ("TEST_SYMBOL_STRATEGY_DATA_MANAGER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_LOADER = ("TEST_SYMBOL_STRATEGY_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_WRITER = ("TEST_SYMBOL_STRATEGY_DATA_WRITER", logging.ERROR)

    ## FEATURE ENGINEERING
    FEATURE_ENGINEERING = ("TEST_FEATURE_ENGINEERING", logging.ERROR)
    FEATURE_ENGINEER = ("TEST_FEATURE_ENGINEER", logging.ERROR)

    ## DATA PREP
    BACKTEST_DATA_INGEST = ("TEST_BACKTEST_DATA_INGEST", logging.ERROR)
    BACKTEST_FEATURE_ENGINEERING = ("TEST_BACKTEST_FEATURE_ENGINEERING", logging.ERROR)

    ## SIGNAL STRATEGY
    SIGNAL_STRATEGY = ("TEST_SIGNAL_STRATEGY", logging.ERROR)
    SIGNAL_STRATEGY_FACTORY = ("TEST_SIGNAL_STRATEGY_FACTORY", logging.ERROR)
    SIGNAL_STRATEGY_COMBINATOR_FACTORY = (
        "TEST_SIGNAL_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_OPTIMIZER_FACTORY = (
        "TEST_SIGNAL_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY BACKTESTING
    SIGNAL_STRATEGY_EXECUTOR = ("TEST_SIGNAL_STRATEGY_EXECUTOR", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATOR = ("TEST_SIGNAL_STRATEGY_EVALUATOR", logging.ERROR)
    SIGNAL_STRATEGY_OPTIMIZATION = ("TEST_SIGNAL_STRATEGY_OPTIMIZATION", logging.ERROR)
    SIGNAL_STRATEGY_TESTING = ("TEST_SIGNAL_STRATEGY_TESTING", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATION = ("TEST_SIGNAL_STRATEGY_EVALUATION", logging.ERROR)
    SYMBOL_EVALUATION = ("TEST_SYMBOL_EVALUATION", logging.ERROR)
    SIGNAL_STRATEGY_WALK_FORWARD = ("TEST_SIGNAL_STRATEGY_WALK_FORWARD", logging.ERROR)

    ## PORTFOLIO STRATEGY
    PORTFOLIO_STRATEGY = ("TEST_PORTFOLIO_STRATEGY", logging.ERROR)
    PORTFOLIO_STRATEGY_COMBINATOR_FACTORY = (
        "TEST_PORTFOLIO_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY = (
        "TEST_PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## PORTFOLIO BACKTESTING
    PORTFOLIO_BACKTEST_EXECUTOR = ("TEST_PORTFOLIO_BACKTEST_EXECUTOR", logging.ERROR)
    PORTFOLIO_BACKTEST_EVALUATOR = ("TEST_PORTFOLIO_BACKTEST_EVALUATOR", logging.ERROR)
    PORTFOLIO_ASSET_MATRIX_PREPARER = (
        "TEST_PORTFOLIO_ASSET_MATRIX_PREPARER",
        logging.ERROR,
    )
    PORTFOLIO_MATRIX_LOADER = ("TEST_PORTFOLIO_MATRIX_LOADER", logging.ERROR)
    PORTFOLIO_OPTIMIZATION = ("TEST_PORTFOLIO_OPTIMIZATION", logging.ERROR)
    PORTFOLIO_TESTING = ("TEST_PORTFOLIO_TESTING", logging.ERROR)
    PORTFOLIO_WALK_FORWARD = ("TEST_PORTFOLIO_WALK_FORWARD", logging.ERROR)
    PORTFOLIO_CROSS_WINDOW_EVALUATOR = (
        "TEST_PORTFOLIO_CROSS_WINDOW_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_CROSS_STRATEGY_SUMMARY = (
        "TEST_PORTFOLIO_CROSS_STRATEGY_SUMMARY",
        logging.ERROR,
    )
    PORTFOLIO_EVALUATION = ("TEST_PORTFOLIO_EVALUATION", logging.ERROR)

    ## LEDGER SERVICES
    ACCOUNT_CASH_SERVICE = ("TEST_ACCOUNT_CASH_SERVICE", logging.ERROR)
    CLOCK_SERVICE = ("TEST_CLOCK_SERVICE", logging.ERROR)
    ENRICHED_DATA_SERVICE = ("TEST_ENRICHED_DATA_SERVICE", logging.ERROR)
    ORDER_SERVICE = ("TEST_ORDER_SERVICE", logging.ERROR)
    TRADE_SERVICE = ("TEST_TRADE_SERVICE", logging.ERROR)
    POSITION_SERVICE = ("TEST_POSITION_SERVICE", logging.ERROR)
    LEDGER_SERVICE = ("TEST_LEDGER_SERVICE", logging.ERROR)

    ## MARKET SESSION

    ORDER_EXECUTION_SERVICE = ("TEST_ORDER_EXECUTION_SERVICE", logging.ERROR)
    ORDER_MONITOR_SERVICE = ("TEST_ORDER_MONITOR_SERVICE", logging.ERROR)
    MARKET_SESSION_SERVICE = ("TEST_MARKET_SESSION_SERVICE", logging.ERROR)

    ## ORDER GENERATION
    MARKET_DATA_RAW_STREAMER = ("TEST_MARKET_DATA_RAW_STREAMER", logging.ERROR)
    MARKET_DATA_ENRICHED_STREAMER = (
        "TEST_MARKET_DATA_ENRICHED_STREAMER",
        logging.ERROR,
    )
    SIGNAL_GENERATOR = ("TEST_SIGNAL_GENERATOR", logging.ERROR)
    ORDER_GENERATOR = ("TEST_ORDER_GENERATOR", logging.ERROR)
    SYMBOL_SERVICE = ("TEST_SYMBOL_SERVICE", logging.ERROR)
    ORDER_EVENT_SERVICE = ("TEST_ORDER_EVENT_SERVICE", logging.ERROR)
    SYMBOL_HOLD_TRACKER = ("TEST_SYMBOL_HOLD_TRACKER", logging.ERROR)
    SYMBOL_HOLD_SERVICE = ("TEST_SYMBOL_HOLD_SERVICE", logging.ERROR)
    ORDER_GENERATOR_SERVICE = ("TEST_ORDER_GENERATOR_SERVICE", logging.ERROR)

    # REGISTRY
    SIGNAL_STRATEGY_REGISTRY = ("TEST_SIGNAL_STRATEGY_REGISTRY", logging.ERROR)
    PORTFOLIO_STRATEGY_REGISTRY = ("TEST_PORTFOLIO_STRATEGY_REGISTRY", logging.ERROR)

    ## BACKTEST PIPELINE
    PIPELINE_COORDINATOR = ("TEST_PIPELINE_COORDINATOR", logging.ERROR)

    ## TRADE ORCHESTRATOR
    TRADE_ORCHESTRATOR = ("TEST_TRADE_ORCHESTRATOR", logging.ERROR)

    @property
    def name_str(self):
        return self.value[0]

    @property
    def log_level(self):
        return self.value[1]

    @property
    def print_logs(self):
        return self.value[2] if len(self.value) > 2 else False
