import logging
from enum import Enum


class EnvLoggerTypeProd(Enum):
    ## DATABASE
    DATABASE = ("PROD_DATABASE", logging.ERROR)

    ## DAOS
    DATA_STREAM_SESSION_DAO = ("PROD_DATA_STREAM_SESSION_DAO", logging.ERROR)
    ENRICHED_DATA_DAO = ("PROD_ENRICHED_DATA_DAO", logging.ERROR)
    TRADE_DAO = ("PROD_TRADE_DAO", logging.ERROR)
    ORDER_DAO = ("PROD_ORDER_DAO", logging.ERROR)

    ## REPOSITORIES
    DATA_STREAM_SESSION_REPO = ("PROD_DATA_STREAM_SESSION_REPO", logging.ERROR)
    ENRICHED_DATA_REPO = ("PROD_ENRICHED_DATA_REPO", logging.ERROR)
    TRADE_REPO = ("PROD_TRADE_REPO", logging.ERROR)
    ORDER_REPO = ("PROD_ORDER_REPO", logging.ERROR)
    WATCHLIST_REPO = ("PROD_WATCHLIST_REPO", logging.ERROR)

    ## ALPACA CLIENTS
    ALPACA_CORPORATE_ACTION_CLIENT = (
        "PROD_ALPACA_CORPORATE_ACTION_CLIENT",
        logging.ERROR,
    )
    ALPACA_NEWS_CLIENT = ("PROD_ALPACA_NEWS_CLIENT", logging.ERROR)
    ALPACA_SCREENER_CLIENT = ("PROD_ALPACA_SCREENER_CLIENT", logging.ERROR)
    ALPACA_STOCK_CLIENT = ("PROD_ALPACA_STOCK_CLIENT", logging.ERROR)
    ALPACA_STREAM_CLIENT = ("PROD_ALPACA_STREAM_CLIENT", logging.ERROR)
    ALPACA_ORDER_STREAM_CLIENT = ("PROD_ALPACA_ORDER_STREAM_CLIENT", logging.ERROR)
    ALPACA_ACCOUNT_CLIENT = ("PROD_ALPACA_ACCOUNT_CLIENT", logging.ERROR)
    ALPACA_ASSETS_CLIENT = ("PROD_ALPACA_ASSETS_CLIENT", logging.ERROR)
    ALPACA_CALENDAR_CLIENT = ("PROD_ALPACA_CALENDAR_CLIENT", logging.ERROR)
    ALPACA_CLOCK_CLIENT = ("PROD_ALPACA_CLOCK_CLIENT", logging.ERROR)
    ALPACA_ORDERS_CLIENT = ("PROD_ALPACA_ORDERS_CLIENT", logging.ERROR)
    ALPACA_PORTFOLIO_CLIENT = ("PROD_ALPACA_PORTFOLIO_CLIENT", logging.ERROR)
    ALPACA_POSITIONS_CLIENT = ("PROD_ALPACA_POSITIONS_CLIENT", logging.ERROR)
    ALPACA_WATCHLIST_CLIENT = ("PROD_ALPACA_WATCHLIST_CLIENT", logging.ERROR)

    ## ADAPTERS
    CORPORATE_ACTION_ADAPTER = ("PROD_CORPORATE_ACTION_ADAPTER", logging.ERROR)
    NEWS_ADAPTER = ("PROD_NEWS_ADAPTER", logging.ERROR)
    SCREENER_ADAPTER = ("PROD_SCREENER_ADAPTER", logging.ERROR)
    QUOTE_ADAPTER = ("PROD_QUOTE_ADAPTER", logging.ERROR)
    STREAM_ADAPTER = ("PROD_STREAM_ADAPTER", logging.ERROR)
    ACCOUNT_ADAPTER = ("PROD_ACCOUNT_ADAPTER", logging.ERROR)
    ASSETS_ADAPTER = ("PROD_ASSETS_ADAPTER", logging.ERROR)
    CALENDAR_ADAPTER = ("PROD_CALENDAR_ADAPTER", logging.ERROR)
    CLOCK_ADAPTER = ("PROD_CLOCK_ADAPTER", logging.ERROR)
    ORDER_STREAM_ADAPTER = ("PROD_ORDER_STREAM_ADAPTER", logging.ERROR)
    ORDERS_ADAPTER = ("PROD_ORDERS_ADAPTER", logging.ERROR)
    PORTFOLIO_ADAPTER = ("PROD_PORTFOLIO_ADAPTER", logging.ERROR)
    POSITIONS_ADAPTER = ("PROD_POSITIONS_ADAPTER", logging.ERROR)
    WATCHLIST_ADAPTER = ("PROD_WATCHLIST_ADAPTER", logging.ERROR)

    ## STAGE DATA
    STAGE_DATA_MANAGER = ("PROD_STAGE_DATA_MANAGER", logging.ERROR)
    STAGE_DATA_PREPARER = ("PROD_STAGE_DATA_PREPARER", logging.ERROR)
    STAGE_DATA_WRITER = ("PROD_STAGE_DATA_WRITER", logging.ERROR)
    STAGE_DATA_LOADER = ("PROD_STAGE_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_MANAGER = ("PROD_SYMBOL_STRATEGY_DATA_MANAGER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_LOADER = ("PROD_SYMBOL_STRATEGY_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_WRITER = ("PROD_SYMBOL_STRATEGY_DATA_WRITER", logging.ERROR)

    ## FEATURE ENGINEERING
    FEATURE_ENGINEERING = ("PROD_FEATURE_ENGINEERING", logging.ERROR)
    FEATURE_ENGINEER = ("PROD_FEATURE_ENGINEER", logging.ERROR)

    ## DATA PREP
    BACKPROD_DATA_INGEST = ("PROD_BACKPROD_DATA_INGEST", logging.ERROR)
    BACKPROD_FEATURE_ENGINEERING = ("PROD_BACKPROD_FEATURE_ENGINEERING", logging.ERROR)

    ## SIGNAL STRATEGY
    SIGNAL_STRATEGY = ("PROD_SIGNAL_STRATEGY", logging.ERROR)
    SIGNAL_STRATEGY_FACTORY = ("PROD_SIGNAL_STRATEGY_FACTORY", logging.ERROR)
    SIGNAL_STRATEGY_COMBINATOR_FACTORY = (
        "PROD_SIGNAL_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_OPTIMIZER_FACTORY = (
        "PROD_SIGNAL_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY BACKTESTING
    SIGNAL_STRATEGY_EXECUTOR = ("PROD_SIGNAL_STRATEGY_EXECUTOR", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATOR = ("PROD_SIGNAL_STRATEGY_EVALUATOR", logging.ERROR)
    SIGNAL_STRATEGY_OPTIMIZATION = ("PROD_SIGNAL_STRATEGY_OPTIMIZATION", logging.ERROR)
    SIGNAL_STRATEGY_TESTING = ("PROD_SIGNAL_STRATEGY_TESTING", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATION = ("PROD_SIGNAL_STRATEGY_EVALUATION", logging.ERROR)
    SYMBOL_EVALUATION = ("PROD_SYMBOL_EVALUATION", logging.ERROR)
    SIGNAL_STRATEGY_WALK_FORWARD = ("PROD_SIGNAL_STRATEGY_WALK_FORWARD", logging.ERROR)

    ## PORTFOLIO STRATEGY
    PORTFOLIO_STRATEGY = ("PROD_PORTFOLIO_STRATEGY", logging.ERROR)
    PORTFOLIO_STRATEGY_COMBINATOR_FACTORY = (
        "PROD_PORTFOLIO_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY = (
        "PROD_PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## PORTFOLIO BACKTESTING
    PORTFOLIO_BACKPROD_EXECUTOR = ("PROD_PORTFOLIO_BACKPROD_EXECUTOR", logging.ERROR)
    PORTFOLIO_BACKPROD_EVALUATOR = ("PROD_PORTFOLIO_BACKPROD_EVALUATOR", logging.ERROR)
    PORTFOLIO_ASSET_MATRIX_PREPARER = (
        "PROD_PORTFOLIO_ASSET_MATRIX_PREPARER",
        logging.ERROR,
    )
    PORTFOLIO_MATRIX_LOADER = ("PROD_PORTFOLIO_MATRIX_LOADER", logging.ERROR)
    PORTFOLIO_OPTIMIZATION = ("PROD_PORTFOLIO_OPTIMIZATION", logging.ERROR)
    PORTFOLIO_TESTING = ("PROD_PORTFOLIO_TESTING", logging.ERROR)
    PORTFOLIO_WALK_FORWARD = ("PROD_PORTFOLIO_WALK_FORWARD", logging.ERROR)
    PORTFOLIO_CROSS_WINDOW_EVALUATOR = (
        "PROD_PORTFOLIO_CROSS_WINDOW_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_CROSS_STRATEGY_SUMMARY = (
        "PROD_PORTFOLIO_CROSS_STRATEGY_SUMMARY",
        logging.ERROR,
    )
    PORTFOLIO_EVALUATION = ("PROD_PORTFOLIO_EVALUATION", logging.ERROR)

    ## LEDGER SERVICES
    ACCOUNT_CASH_SERVICE = ("PROD_ACCOUNT_CASH_SERVICE", logging.ERROR)
    CLOCK_SERVICE = ("PROD_CLOCK_SERVICE", logging.ERROR)
    ENRICHED_DATA_SERVICE = ("PROD_ENRICHED_DATA_SERVICE", logging.ERROR)
    ORDER_SERVICE = ("PROD_ORDER_SERVICE", logging.ERROR)
    TRADE_SERVICE = ("PROD_TRADE_SERVICE", logging.ERROR)
    POSITION_SERVICE = ("PROD_POSITION_SERVICE", logging.ERROR)
    LEDGER_SERVICE = ("PROD_LEDGER_SERVICE", logging.ERROR)

    ## MARKET SESSION

    ORDER_EXECUTION_SERVICE = ("PROD_ORDER_EXECUTION_SERVICE", logging.ERROR)
    ORDER_MONITOR_SERVICE = ("PROD_ORDER_MONITOR_SERVICE", logging.ERROR)
    MARKET_SESSION_SERVICE = ("PROD_MARKET_SESSION_SERVICE", logging.ERROR)

    ## ORDER GENERATION
    MARKET_DATA_RAW_STREAMER = ("PROD_MARKET_DATA_RAW_STREAMER", logging.ERROR)
    MARKET_DATA_ENRICHED_STREAMER = (
        "PROD_MARKET_DATA_ENRICHED_STREAMER",
        logging.ERROR,
    )
    SIGNAL_GENERATOR = ("PROD_SIGNAL_GENERATOR", logging.ERROR)
    ORDER_GENERATOR = ("PROD_ORDER_GENERATOR", logging.ERROR)
    SYMBOL_SERVICE = ("PROD_SYMBOL_SERVICE", logging.ERROR)
    ORDER_EVENT_SERVICE = ("PROD_ORDER_EVENT_SERVICE", logging.ERROR)
    SYMBOL_HOLD_TRACKER = ("PROD_SYMBOL_HOLD_TRACKER", logging.ERROR)
    SYMBOL_HOLD_SERVICE = ("PROD_SYMBOL_HOLD_SERVICE", logging.ERROR)
    ORDER_GENERATOR_SERVICE = ("PROD_ORDER_GENERATOR_SERVICE", logging.ERROR)

    # REGISTRY
    SIGNAL_STRATEGY_REGISTRY = ("PROD_SIGNAL_STRATEGY_REGISTRY", logging.ERROR)
    PORTFOLIO_STRATEGY_REGISTRY = ("PROD_PORTFOLIO_STRATEGY_REGISTRY", logging.ERROR)

    ## BACKTEST PIPELINE
    PIPELINE_COORDINATOR = ("PROD_PIPELINE_COORDINATOR", logging.ERROR)

    ## TRADE ORCHESTRATOR
    TRADE_ORCHESTRATOR = ("PROD_TRADE_ORCHESTRATOR", logging.ERROR)

    @property
    def name_str(self):
        return self.value[0]

    @property
    def log_level(self):
        return self.value[1]

    @property
    def print_logs(self):
        return self.value[2] if len(self.value) > 2 else False
