import logging
from enum import Enum


class EnvLoggerTypeUnit(Enum):
    ## DATABASE
    DATABASE = ("UNIT_DATABASE", logging.ERROR)

    ## DAOS
    DATA_STREAM_SESSION_DAO = ("UNIT_DATA_STREAM_SESSION_DAO", logging.ERROR)
    ENRICHED_DATA_DAO = ("UNIT_ENRICHED_DATA_DAO", logging.ERROR)
    TRADE_DAO = ("UNIT_TRADE_DAO", logging.ERROR)
    ORDER_DAO = ("UNIT_ORDER_DAO", logging.ERROR)

    ## REPOSITORIES
    DATA_STREAM_SESSION_REPO = ("UNIT_DATA_STREAM_SESSION_REPO", logging.ERROR)
    ENRICHED_DATA_REPO = ("UNIT_ENRICHED_DATA_REPO", logging.ERROR)
    TRADE_REPO = ("UNIT_TRADE_REPO", logging.ERROR)
    ORDER_REPO = ("UNIT_ORDER_REPO", logging.ERROR)
    WATCHLIST_REPO = ("UNIT_WATCHLIST_REPO", logging.ERROR)

    ## ALPACA CLIENTS
    ALPACA_CORPORATE_ACTION_CLIENT = (
        "UNIT_ALPACA_CORPORATE_ACTION_CLIENT",
        logging.ERROR,
    )
    ALPACA_NEWS_CLIENT = ("UNIT_ALPACA_NEWS_CLIENT", logging.ERROR)
    ALPACA_SCREENER_CLIENT = ("UNIT_ALPACA_SCREENER_CLIENT", logging.ERROR)
    ALPACA_STOCK_CLIENT = ("UNIT_ALPACA_STOCK_CLIENT", logging.ERROR)
    ALPACA_STREAM_CLIENT = ("UNIT_ALPACA_STREAM_CLIENT", logging.ERROR)
    ALPACA_ORDER_STREAM_CLIENT = ("UNIT_ALPACA_ORDER_STREAM_CLIENT", logging.ERROR)
    ALPACA_ACCOUNT_CLIENT = ("UNIT_ALPACA_ACCOUNT_CLIENT", logging.ERROR)
    ALPACA_ASSETS_CLIENT = ("UNIT_ALPACA_ASSETS_CLIENT", logging.ERROR)
    ALPACA_CALENDAR_CLIENT = ("UNIT_ALPACA_CALENDAR_CLIENT", logging.ERROR)
    ALPACA_CLOCK_CLIENT = ("UNIT_ALPACA_CLOCK_CLIENT", logging.ERROR)
    ALPACA_ORDERS_CLIENT = ("UNIT_ALPACA_ORDERS_CLIENT", logging.ERROR)
    ALPACA_PORTFOLIO_CLIENT = ("UNIT_ALPACA_PORTFOLIO_CLIENT", logging.ERROR)
    ALPACA_POSITIONS_CLIENT = ("UNIT_ALPACA_POSITIONS_CLIENT", logging.ERROR)
    ALPACA_WATCHLIST_CLIENT = ("UNIT_ALPACA_WATCHLIST_CLIENT", logging.ERROR)

    ## ADAPTERS
    CORPORATE_ACTION_ADAPTER = ("UNIT_CORPORATE_ACTION_ADAPTER", logging.ERROR)
    NEWS_ADAPTER = ("UNIT_NEWS_ADAPTER", logging.ERROR)
    SCREENER_ADAPTER = ("UNIT_SCREENER_ADAPTER", logging.ERROR)
    QUOTE_ADAPTER = ("UNIT_QUOTE_ADAPTER", logging.ERROR)
    STREAM_ADAPTER = ("UNIT_STREAM_ADAPTER", logging.ERROR)
    ACCOUNT_ADAPTER = ("UNIT_ACCOUNT_ADAPTER", logging.ERROR)
    ASSETS_ADAPTER = ("UNIT_ASSETS_ADAPTER", logging.ERROR)
    CALENDAR_ADAPTER = ("UNIT_CALENDAR_ADAPTER", logging.ERROR)
    CLOCK_ADAPTER = ("UNIT_CLOCK_ADAPTER", logging.ERROR)
    ORDER_STREAM_ADAPTER = ("UNIT_ORDER_STREAM_ADAPTER", logging.ERROR)
    ORDERS_ADAPTER = ("UNIT_ORDERS_ADAPTER", logging.ERROR)
    PORTFOLIO_ADAPTER = ("UNIT_PORTFOLIO_ADAPTER", logging.ERROR)
    POSITIONS_ADAPTER = ("UNIT_POSITIONS_ADAPTER", logging.ERROR)
    WATCHLIST_ADAPTER = ("UNIT_WATCHLIST_ADAPTER", logging.ERROR)

    ## STAGE DATA
    STAGE_DATA_MANAGER = ("UNIT_STAGE_DATA_MANAGER", logging.ERROR)
    STAGE_DATA_PREPARER = ("UNIT_STAGE_DATA_PREPARER", logging.ERROR)
    STAGE_DATA_WRITER = ("UNIT_STAGE_DATA_WRITER", logging.ERROR)
    STAGE_DATA_LOADER = ("UNIT_STAGE_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_MANAGER = ("UNIT_SYMBOL_STRATEGY_DATA_MANAGER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_LOADER = ("UNIT_SYMBOL_STRATEGY_DATA_LOADER", logging.ERROR)
    SYMBOL_STRATEGY_DATA_WRITER = ("UNIT_SYMBOL_STRATEGY_DATA_WRITER", logging.ERROR)

    ## FEATURE ENGINEERING
    FEATURE_ENGINEERING = ("UNIT_FEATURE_ENGINEERING", logging.ERROR)
    FEATURE_ENGINEER = ("UNIT_FEATURE_ENGINEER", logging.ERROR)

    ## DATA PREP
    BACKUNIT_DATA_INGEST = ("UNIT_BACKUNIT_DATA_INGEST", logging.ERROR)
    BACKUNIT_FEATURE_ENGINEERING = ("UNIT_BACKUNIT_FEATURE_ENGINEERING", logging.ERROR)

    ## SIGNAL STRATEGY
    SIGNAL_STRATEGY = ("UNIT_SIGNAL_STRATEGY", logging.ERROR)
    SIGNAL_STRATEGY_FACTORY = ("UNIT_SIGNAL_STRATEGY_FACTORY", logging.ERROR)
    SIGNAL_STRATEGY_COMBINATOR_FACTORY = (
        "UNIT_SIGNAL_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    SIGNAL_STRATEGY_OPTIMIZER_FACTORY = (
        "UNIT_SIGNAL_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## SIGNAL STRATEGY BACKTESTING
    SIGNAL_STRATEGY_EXECUTOR = ("UNIT_SIGNAL_STRATEGY_EXECUTOR", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATOR = ("UNIT_SIGNAL_STRATEGY_EVALUATOR", logging.ERROR)
    SIGNAL_STRATEGY_OPTIMIZATION = ("UNIT_SIGNAL_STRATEGY_OPTIMIZATION", logging.ERROR)
    SIGNAL_STRATEGY_TESTING = ("UNIT_SIGNAL_STRATEGY_TESTING", logging.ERROR)
    SIGNAL_STRATEGY_EVALUATION = ("UNIT_SIGNAL_STRATEGY_EVALUATION", logging.ERROR)
    SYMBOL_EVALUATION = ("UNIT_SYMBOL_EVALUATION", logging.ERROR)
    SIGNAL_STRATEGY_WALK_FORWARD = ("UNIT_SIGNAL_STRATEGY_WALK_FORWARD", logging.ERROR)

    ## PORTFOLIO STRATEGY
    PORTFOLIO_STRATEGY = ("UNIT_PORTFOLIO_STRATEGY", logging.ERROR)
    PORTFOLIO_STRATEGY_COMBINATOR_FACTORY = (
        "UNIT_PORTFOLIO_STRATEGY_COMBINATOR_FACTORY",
        logging.ERROR,
    )
    PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY = (
        "UNIT_PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY",
        logging.ERROR,
    )

    ## PORTFOLIO BACKTESTING
    PORTFOLIO_BACKUNIT_EXECUTOR = ("UNIT_PORTFOLIO_BACKUNIT_EXECUTOR", logging.ERROR)
    PORTFOLIO_BACKUNIT_EVALUATOR = ("UNIT_PORTFOLIO_BACKUNIT_EVALUATOR", logging.ERROR)
    PORTFOLIO_ASSET_MATRIX_PREPARER = (
        "UNIT_PORTFOLIO_ASSET_MATRIX_PREPARER",
        logging.ERROR,
    )
    PORTFOLIO_MATRIX_LOADER = ("UNIT_PORTFOLIO_MATRIX_LOADER", logging.ERROR)
    PORTFOLIO_OPTIMIZATION = ("UNIT_PORTFOLIO_OPTIMIZATION", logging.ERROR)
    PORTFOLIO_TESTING = ("UNIT_PORTFOLIO_TESTING", logging.ERROR)
    PORTFOLIO_WALK_FORWARD = ("UNIT_PORTFOLIO_WALK_FORWARD", logging.ERROR)
    PORTFOLIO_CROSS_WINDOW_EVALUATOR = (
        "UNIT_PORTFOLIO_CROSS_WINDOW_EVALUATOR",
        logging.ERROR,
    )
    PORTFOLIO_CROSS_STRATEGY_SUMMARY = (
        "UNIT_PORTFOLIO_CROSS_STRATEGY_SUMMARY",
        logging.ERROR,
    )
    PORTFOLIO_EVALUATION = ("UNIT_PORTFOLIO_EVALUATION", logging.ERROR)

    ## LEDGER SERVICES
    ACCOUNT_CASH_SERVICE = ("UNIT_ACCOUNT_CASH_SERVICE", logging.ERROR)
    CLOCK_SERVICE = ("UNIT_CLOCK_SERVICE", logging.ERROR)
    ENRICHED_DATA_SERVICE = ("UNIT_ENRICHED_DATA_SERVICE", logging.ERROR)
    ORDER_SERVICE = ("UNIT_ORDER_SERVICE", logging.ERROR)
    TRADE_SERVICE = ("UNIT_TRADE_SERVICE", logging.ERROR)
    POSITION_SERVICE = ("UNIT_POSITION_SERVICE", logging.ERROR)
    LEDGER_SERVICE = ("UNIT_LEDGER_SERVICE", logging.ERROR)

    ## MARKET SESSION

    ORDER_EXECUTION_SERVICE = ("UNIT_ORDER_EXECUTION_SERVICE", logging.ERROR)
    ORDER_MONITOR_SERVICE = ("UNIT_ORDER_MONITOR_SERVICE", logging.ERROR)
    MARKET_SESSION_SERVICE = ("UNIT_MARKET_SESSION_SERVICE", logging.ERROR)

    ## ORDER GENERATION
    MARKET_DATA_RAW_STREAMER = ("UNIT_MARKET_DATA_RAW_STREAMER", logging.ERROR)
    MARKET_DATA_ENRICHED_STREAMER = (
        "UNIT_MARKET_DATA_ENRICHED_STREAMER",
        logging.ERROR,
    )
    SIGNAL_GENERATOR = ("UNIT_SIGNAL_GENERATOR", logging.ERROR)
    ORDER_GENERATOR = ("UNIT_ORDER_GENERATOR", logging.ERROR)
    SYMBOL_SERVICE = ("UNIT_SYMBOL_SERVICE", logging.ERROR)
    ORDER_EVENT_SERVICE = ("UNIT_ORDER_EVENT_SERVICE", logging.ERROR)
    SYMBOL_HOLD_TRACKER = ("UNIT_SYMBOL_HOLD_TRACKER", logging.ERROR)
    SYMBOL_HOLD_SERVICE = ("UNIT_SYMBOL_HOLD_SERVICE", logging.ERROR)
    ORDER_GENERATOR_SERVICE = ("UNIT_ORDER_GENERATOR_SERVICE", logging.ERROR)

    # REGISTRY
    SIGNAL_STRATEGY_REGISTRY = ("UNIT_SIGNAL_STRATEGY_REGISTRY", logging.ERROR)
    PORTFOLIO_STRATEGY_REGISTRY = ("UNIT_PORTFOLIO_STRATEGY_REGISTRY", logging.ERROR)

    ## BACKTEST PIPELINE
    PIPELINE_COORDINATOR = ("UNIT_PIPELINE_COORDINATOR", logging.ERROR)

    ## TRADE ORCHESTRATOR
    TRADE_ORCHESTRATOR = ("UNIT_TRADE_ORCHESTRATOR", logging.ERROR)

    @property
    def name_str(self):
        return self.value[0]

    @property
    def log_level(self):
        return self.value[1]

    @property
    def print_logs(self):
        return self.value[2] if len(self.value) > 2 else False
