import logging
from enum import Enum


class LoggerType(Enum):
    TRADING = ("TRADING", logging.INFO)
    STAGE_DATA_MANAGER = ("STAGE_DATA_MANAGER", logging.INFO)
    STAGE_DATA_PREPARER = ("STAGE_DATA_PREPARER", logging.INFO)
    STAGE_DATA_WRITER = ("STAGE_DATA_WRITER", logging.INFO)
    STAGE_DATA_LOADER = ("STAGE_DATA_LOADER", logging.INFO)

    STRATEGY_DATA_LOADER = ("STRATEGY_DATA_LOADER", logging.INFO)
    STRATEGY_DATA_WRITER = ("STRATEGY_DATA_WRITER", logging.INFO)

    STRATEGY_EXECUTOR = ("STRATEGY_EXECUTOR", logging.INFO)
    STRATEGY_EVALUATOR = ("STRATEGY_EVALUATOR", logging.INFO)
    STRATEGY_FACTORY = ("STRATEGY_FACTORY", logging.INFO)

    SIGNAL_STRATEGY_OPTIMIZER = ("SIGNAL_STRATEGY_OPTIMIZER", logging.INFO)

    PORTFOLIO_EXECUTOR = ("PORTFOLIO_EXECUTOR", logging.INFO)
    PORTFOLIO_EVALUATOR = ("PORTFOLIO_EVALUATOR", logging.INFO)

    PORTFOLIO_ASSET_MATRIX_PREPARER = ("PORTFOLIO_ASSET_MATRIX_PREPARER", logging.INFO)
    PORTFOLIO_STRATEGY_OPTIMIZER = ("PORTFOLIO_STRATEGY_OPTIMIZER", logging.INFO)

    STRATEGY_EVALUATION = ("STRATEGY_EVALUATION", logging.INFO)
    SYMBOL_EVALUATION = ("SYMBOL_EVALUATION", logging.INFO)
    PORTFOLIO_EVALUATION = ("PORTFOLIO_EVALUATION", logging.INFO)

    BACKTEST_DATA_INGEST = ("BACKTEST_DATA_INGEST", logging.INFO)
    BACKTEST_FEATURE_ENGINEERING = ("BACKTEST_FEATURE_ENGINEERING", logging.INFO)
    BACKTEST_SIGNAL_OPTIMIZATION = ("BACKTEST_SIGNAL_OPTIMIZATION", logging.INFO)
    BACKTEST_SIGNAL_TESTING = ("BACKTEST_SIGNAL_TESTING", logging.INFO)
    BACKTEST_PORTFOLIO_OPTIMIZATION = ("BACKTEST_PORTFOLIO_OPTIMIZATION", logging.INFO)
    BACKTEST_PORTFOLIO_TESTING = ("BACKTEST_PORTFOLIO_TESTING", logging.INFO)

    STRATEGY_WALK_FORWARD = ("STRATEGY_WALK_FORWARD", logging.INFO)
    PORTFOLIO_WALK_FORWARD = ("PORTFOLIO_WALK_FORWARD", logging.INFO)

    BACKTEST_PIPELINE = ("BACKTEST_PIPELINE", logging.INFO)

    WATCHLIST = ("WATCHLIST", logging.INFO)
    TESTING = ("TESTING", logging.INFO)

    @property
    def name_str(self):
        return self.value[0]

    @property
    def log_level(self):
        return self.value[1]
