from enum import Enum


class LoggerType(Enum):
    ## DATABASE
    DATABASE = "DATABASE"

    ## DAOS
    DATA_STREAM_SESSION_DAO = "DATA_STREAM_SESSION_DAO"
    ENRICHED_DATA_DAO = "ENRICHED_DATA_DAO"
    TRADE_DAO = "TRADE_DAO"
    ORDER_DAO = "ORDER_DAO"

    ## REPOSITORIES
    DATA_STREAM_SESSION_REPO = "DATA_STREAM_SESSION_REPO"
    ENRICHED_DATA_REPO = "ENRICHED_DATA_REPO"
    TRADE_REPO = "TRADE_REPO"
    ORDER_REPO = "ORDER_REPO"
    WATCHLIST_REPO = "WATCHLIST_REPO"

    ## ALPACA CLIENTS
    ALPACA_CORPORATE_ACTION_CLIENT = "ALPACA_CORPORATE_ACTION_CLIENT"
    ALPACA_NEWS_CLIENT = "ALPACA_NEWS_CLIENT"
    ALPACA_SCREENER_CLIENT = "ALPACA_SCREENER_CLIENT"
    ALPACA_STOCK_CLIENT = "ALPACA_STOCK_CLIENT"
    ALPACA_STREAM_CLIENT = "ALPACA_STREAM_CLIENT"
    ALPACA_ORDER_STREAM_CLIENT = "ALPACA_ORDER_STREAM_CLIENT"
    ALPACA_ACCOUNT_CLIENT = "ALPACA_ACCOUNT_CLIENT"
    ALPACA_ASSETS_CLIENT = "ALPACA_ASSETS_CLIENT"
    ALPACA_CALENDAR_CLIENT = "ALPACA_CALENDAR_CLIENT"
    ALPACA_CLOCK_CLIENT = "ALPACA_CLOCK_CLIENT"
    ALPACA_ORDERS_CLIENT = "ALPACA_ORDERS_CLIENT"
    ALPACA_PORTFOLIO_CLIENT = "ALPACA_PORTFOLIO_CLIENT"
    ALPACA_POSITIONS_CLIENT = "ALPACA_POSITIONS_CLIENT"
    ALPACA_WATCHLIST_CLIENT = "ALPACA_WATCHLIST_CLIENT"

    ## ADAPTERS
    CORPORATE_ACTION_ADAPTER = "CORPORATE_ACTION_ADAPTER"
    NEWS_ADAPTER = "NEWS_ADAPTER"
    SCREENER_ADAPTER = "SCREENER_ADAPTER"
    QUOTE_ADAPTER = "QUOTE_ADAPTER"
    STREAM_ADAPTER = "STREAM_ADAPTER"
    ACCOUNT_ADAPTER = "ACCOUNT_ADAPTER"
    ASSETS_ADAPTER = "ASSETS_ADAPTER"
    CALENDAR_ADAPTER = "CALENDAR_ADAPTER"
    CLOCK_ADAPTER = "CLOCK_ADAPTER"
    ORDER_STREAM_ADAPTER = "ORDER_STREAM_ADAPTER"
    ORDERS_ADAPTER = "ORDERS_ADAPTER"
    PORTFOLIO_ADAPTER = "PORTFOLIO_ADAPTER"
    POSITIONS_ADAPTER = "POSITIONS_ADAPTER"
    WATCHLIST_ADAPTER = "WATCHLIST_ADAPTER"

    ## STAGE DATA
    STAGE_DATA_MANAGER = "STAGE_DATA_MANAGER"
    STAGE_DATA_PREPARER = "STAGE_DATA_PREPARER"
    STAGE_DATA_WRITER = "STAGE_DATA_WRITER"
    STAGE_DATA_LOADER = "STAGE_DATA_LOADER"
    SYMBOL_STRATEGY_DATA_MANAGER = "SYMBOL_STRATEGY_DATA_MANAGER"
    SYMBOL_STRATEGY_DATA_LOADER = "SYMBOL_STRATEGY_DATA_LOADER"
    SYMBOL_STRATEGY_DATA_WRITER = "SYMBOL_STRATEGY_DATA_WRITER"

    ## FEATURE ENGINEERING
    FEATURE_ENGINEERING = "FEATURE_ENGINEERING"
    FEATURE_ENGINEER = "FEATURE_ENGINEER"

    ## DATA PREP
    BACKDATA_INGEST = "BACKDATA_INGEST"
    BACKFEATURE_ENGINEERING = "BACKFEATURE_ENGINEERING"

    ## SIGNAL STRATEGY
    SIGNAL_STRATEGY = "SIGNAL_STRATEGY"
    SIGNAL_STRATEGY_FACTORY = "SIGNAL_STRATEGY_FACTORY"
    SIGNAL_STRATEGY_COMBINATOR_FACTORY = "SIGNAL_STRATEGY_COMBINATOR_FACTORY"

    SIGNAL_STRATEGY_OPTIMIZER_FACTORY = "SIGNAL_STRATEGY_OPTIMIZER_FACTORY"

    ## SIGNAL STRATEGY BACKTESTING
    SIGNAL_STRATEGY_EXECUTOR = "SIGNAL_STRATEGY_EXECUTOR"
    SIGNAL_STRATEGY_EVALUATOR = "SIGNAL_STRATEGY_EVALUATOR"
    SIGNAL_STRATEGY_OPTIMIZATION = "SIGNAL_STRATEGY_OPTIMIZATION"
    SIGNAL_STRATEGY_TESTING = "SIGNAL_STRATEGY_TESTING"
    SIGNAL_STRATEGY_EVALUATION = "SIGNAL_STRATEGY_EVALUATION"
    SYMBOL_EVALUATION = "SYMBOL_EVALUATION"
    SIGNAL_STRATEGY_WALK_FORWARD = "SIGNAL_STRATEGY_WALK_FORWARD"

    ## PORTFOLIO STRATEGY
    PORTFOLIO_STRATEGY = "PORTFOLIO_STRATEGY"
    PORTFOLIO_STRATEGY_COMBINATOR_FACTORY = ("PORTFOLIO_STRATEGY_COMBINATOR_FACTORY",)
    PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY = "PORTFOLIO_STRATEGY_OPTIMIZER_FACTORY"

    ## PORTFOLIO BACKTESTING
    PORTFOLIO_BACKEXECUTOR = "PORTFOLIO_BACKEXECUTOR"
    PORTFOLIO_BACKEVALUATOR = "PORTFOLIO_BACKEVALUATOR"
    PORTFOLIO_ASSET_MATRIX_PREPARER = "PORTFOLIO_ASSET_MATRIX_PREPARER"
    PORTFOLIO_MATRIX_LOADER = "PORTFOLIO_MATRIX_LOADER"
    PORTFOLIO_OPTIMIZATION = "PORTFOLIO_OPTIMIZATION"
    PORTFOLIO_TESTING = "PORTFOLIO_TESTING"
    PORTFOLIO_WALK_FORWARD = "PORTFOLIO_WALK_FORWARD"
    PORTFOLIO_CROSS_WINDOW_EVALUATOR = "PORTFOLIO_CROSS_WINDOW_EVALUATOR"
    PORTFOLIO_CROSS_STRATEGY_SUMMARY = "PORTFOLIO_CROSS_STRATEGY_SUMMARY"

    PORTFOLIO_EVALUATION = "PORTFOLIO_EVALUATION"

    ## LEDGER SERVICES
    ACCOUNT_CASH_SERVICE = "ACCOUNT_CASH_SERVICE"
    CLOCK_SERVICE = "CLOCK_SERVICE"
    ENRICHED_DATA_SERVICE = "ENRICHED_DATA_SERVICE"
    ORDER_SERVICE = "ORDER_SERVICE"
    TRADE_SERVICE = "TRADE_SERVICE"
    POSITION_SERVICE = "POSITION_SERVICE"
    LEDGER_SERVICE = "LEDGER_SERVICE"

    ## MARKET SESSION

    ORDER_EXECUTION_SERVICE = "ORDER_EXECUTION_SERVICE"
    ORDER_MONITOR_SERVICE = "ORDER_MONITOR_SERVICE"
    MARKET_SESSION_SERVICE = "MARKET_SESSION_SERVICE"

    ## ORDER GENERATION
    MARKET_DATA_RAW_STREAMER = "MARKET_DATA_RAW_STREAMER"
    MARKET_DATA_ENRICHED_STREAMER = "MARKET_DATA_ENRICHED_STREAMER"
    SIGNAL_GENERATOR = "SIGNAL_GENERATOR"
    ORDER_GENERATOR = "ORDER_GENERATOR"
    SYMBOL_SERVICE = "SYMBOL_SERVICE"
    ORDER_EVENT_SERVICE = "ORDER_EVENT_SERVICE"
    SYMBOL_HOLD_TRACKER = "SYMBOL_HOLD_TRACKER"
    SYMBOL_HOLD_SERVICE = "SYMBOL_HOLD_SERVICE"
    ORDER_GENERATOR_SERVICE = "ORDER_GENERATOR_SERVICE"

    # REGISTRY
    SIGNAL_STRATEGY_REGISTRY = "SIGNAL_STRATEGY_REGISTRY"
    PORTFOLIO_STRATEGY_REGISTRY = "PORTFOLIO_STRATEGY_REGISTRY"

    ## BACKTEST PIPELINE
    PIPELINE_COORDINATOR = "PIPELINE_COORDINATOR"

    ## TRADE ORCHESTRATOR
    TRADE_ORCHESTRATOR = "TRADE_ORCHESTRATOR"
