# algo_royale/logging/loggable.py

from typing import Protocol, runtime_checkable


@runtime_checkable
class Loggable(Protocol):
    def debug(self, msg: str, *args, **kwargs): ...
    def info(self, msg: str, *args, **kwargs): ...
    def warning(self, msg: str, *args, **kwargs): ...
    def error(self, msg: str, *args, **kwargs): ...
    def critical(self, msg: str, *args, **kwargs): ...
    def exception(self, msg: str, *args, **kwargs): ...
